name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app:latest ./todo-app

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/todo-app:latest ${{ secrets.DOCKER_USERNAME }}/go-todo-app:latest

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/go-todo-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install kubectl
        run: |
          sudo apt-get update -y
          sudo apt-get install -y kubectl

      - name: Configure Kubernetes Credentials
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config view 
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./deployment.yml
          kubectl rollout status deployment/todo-app
          kubectl expose deployment todo-app --type=nodePort --name=todo-app-service
          kubectl get pods
          kubectl get svc
